### PR TITLE
[2.x] upgrade to Laravel 9.x and PHP 8.0+

### PR DESCRIPTION
**Pull request by luceos**
This is on top of #250, working through the issues found in that PR to complete the changes for a L9 compatible package.

### CODE REVIEW

**Comment by luceos** [comment]
The following still needs doing:

- [ ] provide a php 8.1 testing image in docker hub
- [ ] `Tenancy\Tests\Framework\Feature\Identification\Concerns\AllowsTenantIdentificationTest::tenant_key_returns_the_model_key` is a test that relies on the tenant key value, which is NULL. This is pretty useless as the tenant key (logically) requires to be either string or int. 
- [ ] `Tenancy\Tests\Database\Mysql\Feature\MysqlConnectionDriverTest::it_deletes_the_database` tests for the PDO exception which in doctrine/dbal 3.3+ is pushed to a new namespace. I've set the minimum constraint for dbal but tests still seem to adopt the older version.
> Failed asserting that exception of type "PDOException" matches expected exception "Doctrine\DBAL\Driver\PDO\Exception". 
- [x] change email logic to remove swift mailer, see other pr

**Comment by luceos** [comment]
@ArlonAntonius the 8.1 image doesn't work. Can you explain how to resolve this?

**Review by ArlonAntonius — DISMISSED** [review]
Thanks for the effort on this PR @mennovanhout & @luceos.

**Review by bretto36 — DISMISSED** [review]

**Comment by bretto36** [comment]
Any ETA on this, it's the only package in our projects that we are waiting on to move to L9. Thank you for the work on this @mennovanhout  and @luceos

**Comment by luceos** [comment]
@bretto36 almost ;)

**Review by ArlonAntonius — APPROVED** [review]

**Comment by bretto36** [comment]
@ArlonAntonius  will you be able to merge this soon by any chance?

**Pull request merged**
