### PR TITLE
Add arguments to pass to the seeder

### LINKED ISSUE #185: Configure seeder doesn't pass arguments & doesn't set tenant
There seems to be an issue within the `ConfigureSeeder` hook

As it doesn't switch the tenant by default, within the Seeds, we cannot retrieve the Tenant that is being configured unless explicitly calling `Tenancy::setTenant($event->event->tenant)` but this causes the issue of not being able to switch back as the seeds are run after
I think the ConfigureSeeder should switch the tenant before the event and switch it back after it automatically

It would also be nice to add the ability to pass parameters to the seed classes so they can use other params

## Actual
```php
<?php

namespace App\Listeners\Tenants;

use PromotionSeeder;
use Tenancy\Hooks\Migration\Events\ConfigureSeeds;

class ConfigureTenantSeeds {
    public function handle(ConfigureSeeds $event) {
        Tenancy::setTenant($event->event->tenant); // If we don't call this tenant will be null in the next call
        $event->seed(PromotionSeeder::class);
        // And then we cannot revert to no tenant after the seeder is executed
    }
}


class PromotionSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        /**
         * @var Tenant $tenant
         */
        $tenant = Tenancy::getTenant();
        // Do something with tenant
   }
}
```
## Expected
```php
class ConfigureTenantSeeds {
    public function handle(ConfigureSeeds $event) {
        $event->seed(PromotionSeeder::class, $event->event->tenant);
    }
}

class PromotionSeeder extends Seeder {
    /**
     * Run the database seeds.
     * @var Tenant $tenant
     * @return void
     */
    public function run($tenant = null) {
       //Do something related to tenant
   }
}
```

### PR DESCRIPTION
**Pull request by Tofandel**
Partially fixes #185

### CODE REVIEW

**Comment by fletch3555** [comment]
We agree this is a problem, but I'm not particularly fond of this solution (see my comments in #185)

**Comment by Tofandel** [comment]
@fletch3555 Could you reopen this PR? As the ability to pass arguments to the seeder will be in laravel 8.x https://github.com/laravel/framework/pull/33737

**Comment by fletch3555** [comment]
We're not planning to add this at this time.

**Comment by Tofandel** [comment]
Any reason why? Laravel 8 has been released now..

**Comment by ArlonAntonius** [comment]
At this moment we don't feel like this is the right solution. This is definitely something we will revisit soonish though. I really appreciate the PR and this might still be the solution in the future, for now just not the way we want to go.

**Pull request closed without merging**
