### PR TITLE
possibility to separate db host, and host of tenants database user 

### PR DESCRIPTION
**Pull request by mgrom**
Additional setting that allows to create tenants database user with host other than database host. This applies only to MySQL.

### CODE REVIEW

**Comment by luceos** [comment]
I am starting to feel less happy about the config file. This sensation happened to me before and I just can't figure out whether to keep it. Perhaps we should try to move some logic into the event itself to make configuration simpler.

Love to hear your opinion too @ArlonAntonius.

**Comment by ArlonAntonius** [comment]
Oke, sorry for the delay on this response, but I wanted to really think about this before giving my answer.

While it might feel like the config doesn't quite feel in the package, I think there's no nice alternative that would fit in the package. Most of the solutions I thought of are not clean enough / up to Laravel standard in order to really put them in the package.

I don't know if @luceos has any amazing ideas to make this properly work without a config if he does, I'm 100% down to discuss them.

However, I think the solution should keep the following in mind:
- It should be easily defaulted (meaning that like now you can simply publish the config, and you have the default setup)
- You can easily adjust the system connection
- You can easily adjust specific pieces of information (like the preset we have at this moment)
- Allowed Host needs to be customizable as easy as possible.

Note: This is just my opinion and view on how things should be. All of this is always open for discussion and if you don't agree with me, I highly recommend you to say so :D

EDIT: We can also make the config smaller or more directed to specific features we want to offer, not sure what the best solution it, but let's all think about it.

**Comment by luceos** [comment]
I'll try to tackle this soon and I'd love to hear whether your above worries will then be nullified. 😬

**Comment by ArlonAntonius** [comment]
Closing this PR as we've solved the problems discussed in this PR with the following PR / Commit (#43)

**Pull request closed without merging**
